[package]
name = "project-agr"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.0"
iced = {version = "0.13", features = ["canvas", "tokio"]}
tokio = { version = "1", features = ["full"] }
native-tls = "0.2"
lazy_static = "1.4"